[package]
name = "dj"
version = "0.3.3"
edition = "2021"
repository = "https://github.com/thinkjones/dj"
description = "macOS developer workstation manager"
license = "MIT"

[[bin]]
name = "dj"
path = "src/main.rs"

[lib]
name = "dj"
path = "src/lib.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
clap_complete = "4"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
gray_matter = "0.2"
pulldown-cmark = "0.11"
similar = "2"
comfy-table = "7"
owo-colors = "4"
dirs = "5"
anyhow = "1"
serde_json = "1"
serde_yaml = "0.9"
sha2 = "0.10"
hex = "0.4"
toml_edit = "0.22"
which = "6"
atty = "0.2"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile = "3"

[profile.release]
strip = true
lto = true
opt-level = 3
