use anyhow::Result;
use owo_colors::OwoColorize;
use dirs::home_dir;

use crate::{
    catalog::{arch_compatible, BrewKind},
    config::{catalog_root, runtime_dir, Config},
    plugins::brew::config::parse as parse_brew,
    plugins::shell::config::parse as parse_shell,
};

const BREWFILE_HEADER: &str =
    "# !! DO NOT HAND-EDIT — generated by dj rebuild from catalog !!\n\n";

pub fn run(cfg: &Config) -> Result<()> {
    println!("{}", "Regenerating catalog artifacts...".cyan());
    regenerate_brewfile(cfg)?;
    regenerate_zshrc(cfg)?;
    println!("{}", "✓ Rebuild complete.".green());
    Ok(())
}

pub fn regenerate_brewfile(cfg: &Config) -> Result<()> {
    let root = catalog_root(cfg);
    let entries = parse_brew(&root.join("brew").join("config.md")).unwrap_or_default();

    let mut brew = String::from(BREWFILE_HEADER);

    let taps: Vec<_> = entries.iter().filter(|e| e.kind == BrewKind::Tap && arch_compatible(&e.arch)).collect();
    let formulae: Vec<_> = entries.iter().filter(|e| e.kind == BrewKind::Formula && arch_compatible(&e.arch)).collect();
    let casks: Vec<_> = entries.iter().filter(|e| e.kind == BrewKind::Cask && arch_compatible(&e.arch)).collect();

    for t in &taps {
        brew.push_str(&format!("tap \"{}\"\n", t.name));
    }
    if !taps.is_empty() { brew.push('\n'); }

    for f in &formulae {
        brew.push_str(&format!("brew \"{}\"\n", f.name));
    }
    if !formulae.is_empty() { brew.push('\n'); }

    for c in &casks {
        brew.push_str(&format!("cask \"{}\"\n", c.name));
    }

    let out_dir = runtime_dir();
    std::fs::create_dir_all(&out_dir)?;
    let out = out_dir.join("Brewfile");
    std::fs::write(&out, &brew)?;
    println!("  Wrote {}", out.display());
    Ok(())
}

pub fn regenerate_zshrc(cfg: &Config) -> Result<()> {
    let root = catalog_root(cfg);
    let shell_functions = parse_shell(&root.join("shell").join("config.md")).unwrap_or_default();
    let brew_entries = parse_brew(&root.join("brew").join("config.md")).unwrap_or_default();
    let home = home_dir().unwrap_or_default();
    let zshrc_path = home.join(".zshrc");

    let mut content = std::fs::read_to_string(&zshrc_path).unwrap_or_default();

    // Shell functions
    let fn_begin = "# === dj:functions begin ===\n";
    let fn_end   = "# === dj:functions end ===\n";
    let mut fn_block = String::from(fn_begin);
    for f in &shell_functions {
        fn_block.push_str(&f.body);
        fn_block.push('\n');
    }
    fn_block.push_str(fn_end);
    content = rewrite_sentinel(&content, fn_begin, fn_end, &fn_block);

    // oh-my-zsh plugins
    let pl_begin = "# === dj:plugins begin ===\n";
    let pl_end   = "# === dj:plugins end ===\n";
    let mut plugins: Vec<&str> = brew_entries.iter()
        .filter(|e| arch_compatible(&e.arch))
        .filter_map(|e| e.zsh_plugin.as_deref())
        .collect();
    plugins.sort_unstable();
    plugins.dedup();
    let pl_line = format!("plugins+=({})\n", plugins.join(" "));
    let pl_block = format!("{}{}{}", pl_begin, pl_line, pl_end);
    content = rewrite_sentinel(&content, pl_begin, pl_end, &pl_block);

    std::fs::write(&zshrc_path, &content)?;
    println!("  Updated {}", zshrc_path.display());
    Ok(())
}

fn rewrite_sentinel(content: &str, begin: &str, end: &str, block: &str) -> String {
    if content.contains(begin) {
        let before = content.split(begin).next().unwrap_or("");
        let after = content.split(end).nth(1).unwrap_or("");
        format!("{}{}{}", before, block, after)
    } else {
        format!("{}\n{}", content.trim_end(), block)
    }
}
