use super::{TranslationFile, TranslationResult};
use crate::permissions::{Decision, PatternCategory, TemplatePermissions};
use anyhow::Result;
use std::path::Path;

pub fn translate(perms: &TemplatePermissions, scope_root: &Path) -> Result<TranslationResult> {
    let config_path = scope_root.join("config.toml");
    let rules_path = scope_root.join("rules").join("00-from-template.rules");

    // --- config.toml using toml_edit ---
    let existing = if config_path.exists() {
        std::fs::read_to_string(&config_path).unwrap_or_default()
    } else {
        String::new()
    };
    let mut doc = existing
        .parse::<toml_edit::DocumentMut>()
        .unwrap_or_default();

    // Owned keys
    doc["approval_policy"] = toml_edit::value("on-request");
    doc["sandbox_mode"] = toml_edit::value("workspace-write");

    // [sandbox_workspace_write]
    let has_network = perms.allow.iter().any(|p| {
        p.category == PatternCategory::WebFetch || p.category == PatternCategory::WebSearch
    });
    {
        let sw = doc
            .entry("sandbox_workspace_write")
            .or_insert(toml_edit::table());
        sw["network_access"] = toml_edit::value(false);
        if has_network {
            // Note: toml_edit doesn't easily add inline comments; note in rules file instead
        }
    }

    let config_content = format!(
        "# >>> dj ai permissions (managed) >>>\n{}# <<< dj ai permissions (managed) <<<\n",
        doc
    );

    // --- Starlark rules ---
    let mut rules = vec![
        "# Generated by dj ai permissions sync".to_string(),
        "# DO NOT EDIT — re-run sync to update".to_string(),
        String::new(),
    ];
    for p in perms.allow.iter().chain(perms.deny.iter()) {
        let decision_str = match p.decision {
            Decision::Allow => "allow",
            Decision::Deny => "deny",
        };
        match p.category {
            PatternCategory::Shell => {
                let cmd = p.shell_base_command().unwrap_or_default();
                rules.push(format!(
                    "# {}\nrule(\"{}\", command_prefix(\"{}\"))",
                    p.raw,
                    decision_str,
                    cmd.trim_end_matches(" *")
                ));
            }
            PatternCategory::Edit | PatternCategory::Read => {
                let action = match p.category {
                    PatternCategory::Edit => "write",
                    _ => "read",
                };
                rules.push(format!(
                    "# {}\nrule(\"{}\", filesystem(\"{}\", \"{}\"))",
                    p.raw, decision_str, action, p.pattern
                ));
            }
            PatternCategory::WebSearch | PatternCategory::WebFetch => {
                rules.push(format!(
                    "# {} -> network rule (not supported in Starlark DSL)",
                    p.raw
                ));
            }
        }
    }
    let rules_content = rules.join("\n") + "\n";

    Ok(TranslationResult {
        files: vec![
            TranslationFile {
                path: config_path,
                content: config_content,
            },
            TranslationFile {
                path: rules_path,
                content: rules_content,
            },
        ],
        warnings: vec![],
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::permissions::{parse_pattern, Decision, TemplatePermissions};
    use tempfile::TempDir;

    fn sample_perms() -> TemplatePermissions {
        let mut tp = TemplatePermissions {
            raw_allow: vec!["Bash(git:*)".to_string()],
            raw_deny: vec!["Bash(rm -rf:*)".to_string()],
            allow: vec![],
            deny: vec![],
        };
        tp.allow
            .push(parse_pattern("Bash(git:*)", Decision::Allow).unwrap());
        tp.deny
            .push(parse_pattern("Bash(rm -rf:*)", Decision::Deny).unwrap());
        tp
    }

    #[test]
    fn translate_creates_config_and_rules() {
        let dir = TempDir::new().unwrap();
        let perms = sample_perms();
        let result = translate(&perms, dir.path()).unwrap();
        assert_eq!(result.files.len(), 2);
        let config = result
            .files
            .iter()
            .find(|f| f.path.ends_with("config.toml"))
            .unwrap();
        assert!(config.content.contains("approval_policy"));
        assert!(config.content.contains("sandbox_mode"));
        let rules = result
            .files
            .iter()
            .find(|f| f.path.ends_with("00-from-template.rules"))
            .unwrap();
        assert!(rules.content.contains("command_prefix"));
    }

    #[test]
    fn translate_config_has_managed_markers() {
        let dir = TempDir::new().unwrap();
        let perms = TemplatePermissions::default();
        let result = translate(&perms, dir.path()).unwrap();
        let config = result
            .files
            .iter()
            .find(|f| f.path.ends_with("config.toml"))
            .unwrap();
        assert!(config
            .content
            .contains(">>> dj ai permissions (managed) >>>"));
        assert!(config
            .content
            .contains("<<< dj ai permissions (managed) <<<"));
    }
}
