use crate::catalog;

use crate::plugins::{Health, HealthStatus, Manifest, PlanStep, Plugin, PluginContext};
use anyhow::Result;

pub mod config;

pub struct Brew {
    manifest: Manifest,
}

impl Default for Brew {
    fn default() -> Self {
        Self::new()
    }
}

impl Brew {
    pub fn new() -> Brew {
        Brew {
            manifest: Manifest::from_toml(include_str!("plugin.toml")).expect("brew manifest"),
        }
    }
    fn entries(ctx: &PluginContext) -> Vec<catalog::BrewEntry> {
        config::parse(&ctx.config_file).unwrap_or_default()
    }
}

impl Plugin for Brew {
    fn manifest(&self) -> &Manifest {
        &self.manifest
    }

    fn plan(&self, ctx: &PluginContext) -> Result<Vec<PlanStep>> {
        Ok(Self::entries(ctx)
            .into_iter()
            .map(|e| PlanStep {
                description: format!(
                    "brew {}: {}",
                    match e.kind {
                        catalog::BrewKind::Cask => "cask",
                        catalog::BrewKind::Tap => "tap",
                        _ => "formula",
                    },
                    e.name
                ),
                mutates: true,
            })
            .collect())
    }

    fn run(&self, ctx: &PluginContext) -> Result<()> {
        if which::which("brew").is_err() {
            println!("brew not found — skipping. Install Homebrew (https://brew.sh) to manage these packages.");
            return Ok(());
        }

        let entries = config::parse(&ctx.config_file)?;
        if entries.is_empty() {
            println!("No brew entries in catalog — skipping.");
            return Ok(());
        }

        // Regenerate Brewfile from parsed entries
        let mut brew = String::from("# !! DO NOT HAND-EDIT — generated by dj from catalog !!\n\n");
        let taps: Vec<_> = entries
            .iter()
            .filter(|e| e.kind == catalog::BrewKind::Tap && catalog::arch_compatible(&e.arch))
            .collect();
        let formulae: Vec<_> = entries
            .iter()
            .filter(|e| e.kind == catalog::BrewKind::Formula && catalog::arch_compatible(&e.arch))
            .collect();
        let casks: Vec<_> = entries
            .iter()
            .filter(|e| e.kind == catalog::BrewKind::Cask && catalog::arch_compatible(&e.arch))
            .collect();

        for t in &taps {
            brew.push_str(&format!("tap \"{}\"\n", t.name));
        }
        if !taps.is_empty() {
            brew.push('\n');
        }

        for f in &formulae {
            brew.push_str(&format!("brew \"{}\"\n", f.name));
        }
        if !formulae.is_empty() {
            brew.push('\n');
        }

        for c in &casks {
            brew.push_str(&format!("cask \"{}\"\n", c.name));
        }

        let out_dir = crate::config::runtime_dir();
        std::fs::create_dir_all(&out_dir)?;
        let out = out_dir.join("Brewfile");
        std::fs::write(&out, &brew)?;
        println!("  Wrote {}", out.display());

        // Run brew bundle
        println!("Running brew bundle...");
        let status = std::process::Command::new("brew")
            .args(["bundle", &format!("--file={}", out.display())])
            .status()?;
        if !status.success() {
            anyhow::bail!("brew bundle failed");
        }
        Ok(())
    }

    fn doctor(&self, ctx: &PluginContext) -> Result<Health> {
        let n = Self::entries(ctx).len();
        let on_path = std::process::Command::new("which")
            .arg("brew")
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false);
        if !on_path {
            return Ok(Health {
                status: HealthStatus::Missing,
                details: vec!["Homebrew not installed".into()],
            });
        }
        Ok(Health {
            status: HealthStatus::Ok,
            details: vec![format!("{n} brew entries in catalog")],
        })
    }

    fn list(&self, ctx: &PluginContext) -> Result<Vec<String>> {
        Ok(Self::entries(ctx).into_iter().map(|e| e.name).collect())
    }

}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cli::scope::ScopeKind;
    #[test]
    fn manifest_loads_and_is_user_scoped() {
        let b = Brew::new();
        assert_eq!(b.manifest().name, "brew");
        assert_eq!(b.manifest().scopes, vec![ScopeKind::User]);
    }
}
