use anyhow::{Context, Result};
use dirs::home_dir;
use serde::Deserialize;
use std::path::PathBuf;

#[derive(Debug, Deserialize, Clone)]
pub struct CatalogMeta {
    pub source: Option<String>, // "example" | "github:owner/repo" | "local"
}

#[derive(Debug, Deserialize, Clone)]
pub struct Config {
    pub catalog_root: PathBuf,
    pub default_agent_stack: String,
    pub catalog: Option<CatalogMeta>,
}

impl Config {
    pub fn load() -> Result<Self> {
        let path = config_path();
        let content = std::fs::read_to_string(&path)
            .with_context(|| format!("cannot read config at {}", path.display()))?;
        toml::from_str(&content).context("invalid config.toml")
    }
}

pub fn config_path() -> PathBuf {
    std::env::var_os("DJ_CONFIG_ROOT")
        .map(PathBuf::from)
        .unwrap_or_else(|| {
            home_dir()
                .unwrap_or_else(|| PathBuf::from("/"))
                .join(".config")
                .join("dj")
                .join("config.toml")
        })
}

pub fn dj_config_dir() -> PathBuf {
    let p = config_path();
    p.parent()
        .map(|d| d.to_path_buf())
        .unwrap_or_else(|| PathBuf::from("."))
}

/// Directory for files generated by dj (Brewfile, etc.). Never inside the catalog.
pub fn runtime_dir() -> PathBuf {
    home_dir()
        .unwrap_or_else(|| PathBuf::from("/"))
        .join(".local")
        .join("share")
        .join("dj")
}

pub fn catalog_root(cfg: &Config) -> PathBuf {
    let raw = cfg.catalog_root.to_string_lossy();
    if raw.starts_with('~') {
        home_dir()
            .unwrap_or_else(|| PathBuf::from("/"))
            .join(raw.trim_start_matches("~/"))
    } else {
        cfg.catalog_root.clone()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use tempfile::NamedTempFile;

    #[test]
    fn config_parses_with_catalog_section() {
        let mut f = NamedTempFile::new().unwrap();
        f.write_all(
            br#"
catalog_root = "/tmp/catalog"
default_agent_stack = "core"

[catalog]
source = "example"
"#,
        )
        .unwrap();
        let content = std::fs::read_to_string(f.path()).unwrap();
        let cfg: Config = toml::from_str(&content).unwrap();
        assert_eq!(cfg.catalog_root, PathBuf::from("/tmp/catalog"));
        assert_eq!(
            cfg.catalog.as_ref().unwrap().source,
            Some("example".to_string())
        );
    }
}
